### PR TITLE
Czech translation

### PR DESCRIPTION
**Pull request by multiflexi**
I created translation to Czech. I think that in English the Advanced settings tab is in reality Camera features. Also I am not sure about the changing word kamera accordingly to number of cameras now it is in this order: Lot of cameras, 2-4 cameras, 1 camera and 1 camera. in English the gstreamer should be GStreamer but that is just minor issue.

### CODE REVIEW

**Comment by exzombie** [comment]
Many thanks, much appreciated! Yeah, I was undecided about "Camera features" vs. "Advanced settings", I may change it when I finally do the inevitable Qt5 port. But I don't understand the issue with the grammatical number. In Qt linguist, I see three fields for Czech: singular, paucal and plural for one, a few and many. Are you saying that, having filled these out correctly, they don't work as they should when the program is run? (I can't check that myself, I'm not familiar with Czech)

**Comment by multiflexi** [comment]
I did not use any software, I just translated the strings when looking at QArv GUI so I understand context. The issue with the word camera is that in Slovenian it has 4 lines there:
 <message numerus="yes">
        <location filename="../src/qarvmainwindow.cpp" line="258"/>
        <source>Found %n cameras.</source>
        <comment>Number of cameras</comment>
        <translation>
            <numerusform>Našel sem %n kamero.</numerusform>
            <numerusform>Našel sem %n kameri.</numerusform>
            <numerusform>Našel sem %n kamere.</numerusform>
            <numerusform>Našel sem %n kamere.</numerusform>
        </translation>
    </message>
and I just dont know what line menas what.

**Comment by exzombie** [comment]
Oh, now I understand. While the `.ts` files can be edited by hand, it helps a lot if you use the Qt linguist program to do it. It shows you the context and explains what each translation field is. It seems to mask fields which are not applicable to a language. For example, in Slovenian it shows singular, dual, trial and plural, while in Czech it shows singular, paucal and plural. So you really should use linguist and check that everything is correct.

**Comment by multiflexi** [comment]
I used the QT linguist. Now it should be correct.

**Comment by exzombie** [comment]
Thank you very much! Sorry it took so long, I missed the notification.

**Pull request merged**
